config/routes.rb
Rails.application.routes.draw do


  resources :users
  resource :session, only:[:new, :destroy, :create]

  resources :subs do
    resources :post, except:[:index]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

    validates :title, :url, :user_id, presence: true

    has_many :post_subs, inverse_of: :post, dependent: :destroy
    has_many :subs, through: :post_subs, source: :sub

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true

  belongs_to :post, inverse_of: :post_subs
  belongs_to :sub, inverse_of: :post_subs

end

app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :moderator_id, :description, presence: true
  validates :name, presence: true, uniqueness: true

  has_many :post_subs,
    class_name: :PostSub,
    primary_key: :id,
    foreign_key: :sub_id

  has_many :posts,
    through: :post_subs,
    source: :post

  belongs_to :moderator,
    class_name: :User,
    primary_key: :id,
    foreign_key: :moderator_id

end

app/models/user.rb
require 'securerandom'


class User < ActiveRecord::Base
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    potential_user = User.find_by_username(username)
    return nil unless potential_user
    potential_user.is_password?(password) ? potential_user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  private
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :logout!


  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logged_in?
    return nil if current_user.nil?
    current_user.session_token == session[:session_token]
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def new
    @post = Post.new
    render :new
  end

  def edit
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to subs_url
    else
      render :new
    end
  end

  def create
    @user = User.find_by_credentials(
      session_params[:username],
      session_params[:password])
    if @user
      login_user!(@user)
      redirect_to subs_url
    else
      flash[:errors] =  @user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to subs_url
  end
  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, except: [:index, :new, :create, :show]
  def index
    @subs = Sub.all
    render :index
  end

  def new
    if logged_in?
      @sub = Sub.new
      render :new
    else
      redirect_to subs_url
    end
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    end
  end

  def show

    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if  @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:moderator_id, :name, :description)
  end

  def require_moderator
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.moderator_id
      flash.now[:errors] ||= []
      flash.now[:errors] << "You have to be a moderator to edit!"
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if logged_in?
      redirect_to users_url
    else
      @user = User.new
      render :new
    end
  end

  def index
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_form.html.erb
<h1> <%= status %></h1>

<% if status == "Sign Up" %>
  <% username_key = "user[username]" %>
  <% password_key = "user[password]" %>
  <% opposite = 'Log in' %>
  <% opposite_action = new_session_url %>
<% else %>
  <% username_key = "session[username]" %>
  <% password_key = "session[password]" %>
  <% opposite = 'Sign Up' %>
  <% opposite_action = new_user_url %>
<% end %>
<% unless logged_in? %>
<%= button_to opposite, opposite_action, method: :get %>
<% end %>
<br>
<% status == "Sign Up" ? username_key = "user[username]" : username_key = "session[username]"%>
<% status == "Sign Up" ? password_key = "user[password]" : password_key = "session[password]"%>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

<label> Username

  <input
    type = "text"
    name = <%= username_key %>

</label>


<br><br>


<label> Password

  <input
    type = "text"
    name = <%= password_key %>

</label>

<br><br>
<%= button_to status  %>

</form>

app/views/partials/_logbutton.html.erb
<h1> <%=button_to  'Home', subs_url, method: :get%>  </h1>




<% if logged_in? %>
<%=  button_to 'Log out', session_url, method: :delete %>
<% else %>
<%= button_to 'Log in', new_session_url, method: :get %>
<% end %>

app/views/post/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <input type="hidden" name="post[user_id]" value = <%= current_user.id  %>>
<label> Post title

  <input
    type = "text"
    name = post[title]
    value="<%= post.title %>"
</label>


<br><br>


<label> Description

  <textarea name="post[content]"><%= post.content %></textarea>
</label>

<br><br>
<%= button_to status  %>

</form>

app/views/post/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

app/views/post/new.html.erb
<h1>Write your new post!</h1>

<%= render 'form', post: @post,  action: sub_post_index_url, method: :post, status: "submit new post" %>

app/views/post/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>

app/views/subs/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <input type="hidden" name="sub[moderator_id]" value= <%= current_user.id unless current_user.nil?%>>
<label> Subreddit name

  <input
    type = "text"
    name = sub[name]
    value="<%= sub.name %>"
</label>


<br><br>


<label> Description

  <textarea name="sub[description]"><%= sub.description %></textarea>
</label>

<br><br>
<%= button_to status  %>

</form>

app/views/subs/edit.html.erb
<%= render 'partials/logbutton' %>
<h1>Edit subreddit</h1>
<%= render 'subs/form', sub: @sub, action: sub_url(@sub), method: :patch, status: 'r-edit!' %>

app/views/subs/index.html.erb
<%= render 'partials/logbutton' %>
<h1>All Subreddits</h1>

<br><br>

<%  @subs.all.each do |sub| %>
<%= link_to "#{sub.name}", sub_url(sub.id) %><br><br>
<%  end  %>

<br><br><br>
<%= button_to 'Create new subreddit', new_sub_url, method: :get %>

<% flash[:errors].try(:each) do |key,value| %>
<%= key %>
<% end %>

app/views/subs/new.html.erb
<h1>New Subreddit</h1>
<%= render 'subs/form', sub: @sub, action: subs_url, method: :post, status: 'create subreddit!' %>

app/views/subs/show.html.erb
<%= render 'partials/logbutton' %>
<h1> <%= @sub.name %></h1>
<br>
<div>
<strong><%= User.find_by_id(@sub.moderator_id).username %></strong> is the moderator of this subreddit
</div>
<br><br>
Description: <%= @sub.description %>
<br>
<%= button_to 'edit subreddit', edit_sub_url, method: :get %>
<%= button_to 'submit post', new_sub_post_url(@sub.id), method: :get %>

<% flash[:errors].try(:each) do |key,value| %>
<%= key %>
<% end %>

app/views/users/index.html.erb
<h1> Polkovodets Rumyantsev </h1>

app/views/users/new.html.erb
<%= render 'partials/form', status: "Sign Up", action: users_url, method: :post %>